### ISSUE TITLE
Verge Foundation?

### ISSUE THREAD

**Issue by brianerdelyi** [vergecurrency/vergecurrency.com#258]
Although Verge is not a private company, is there any interest in formalizing an organizational structure for the project?  Perhaps Verge Foundation?

Often, when I consider purchasing a digital currency, I look at the project's website to see how active it is, who's involved and the direction the project is going.  This gives me an idea how organized and mature the team is.  It gives me warm fuzzies or tells me to stay away.

I think formalizing an organizational structure and calling it Verge Foundation will help give others confidence in our project and XVG.

I suspect such an organization may be comprised of a Marketing Team, Software Development Team, Operations Team and Security Team.  Overall, I think there should be one or two people to represent Verge (perhaps referred to as Core Team, Management Team or Project Management Team?) and provide guidance on the direction for each of the teams.

I've proposed a Verge Computer Security Incident Response Team (Verge-CSIRT) and submitted the charter to GitHub.  An organizational structure can help me understand what teams to notify and involve in the event of an incident, reported vulnerability or when publishing security advisories and other guidance.

Thoughts?

**Comment by brianerdelyi** [comment]
Good day.  @justinvforvendetta, can you or anyone else provide some insight into the core management team and other teams that exist?

I found https://medium.com/verge-currency-xvg/meet-the-core-team-our-future-vision-and-an-important-announcement-3965730bd0b8 but expect it may need to be updated.  I'd like to show a hierarchy of the teams involved.

**Comment by elcalavera21** [comment]
Last night I left a sativa + Adderal-fueled rant on the Discord with my thoughts after a month of watching closely. 

@justinvforvendetta you've built something that's got the potential to be a game changer. You've also done it largely by yourself (the code/architecture of it anyways) and the merits of that work and the people supporting you (@CryptoRekt especially it seems) positioned Verge for the rapid ascent it's had since the fall. 

Now this project is worth more than Buzzfeed, Instacart, and rapidly passing the value of Github, this platform.....Justin I think you should very deeply consider setting up a foundation like Brian is suggesting. I'm sure the pressure from all this is wild, especially since there's so many new people who want to help (like me) and you're the only autonomous decision maker. 

I was invited behind the scenes of another coin and they had something similar -- a separate "contributors discord" where marketing, development, design, website etc all had multiple channels buzzing with relevant discussion at all hours. With that, a hierarchy of representation from each department that participates in a weekly meeting on the Discord where every team realigns on goals, progress, ideas, etc. This coin plans to make all of the team leaders consumer-facing -- aka publishing a "team" page with contact info for contributors recruitment and etc. 

I understand that there are already teams of people working behind the scenes at Verge, but I wonder if the way the collaboration is built right now is inefficient or not visible enough. Everyone seems paralyzed to move without Justin's permission, and quite often Justin just doesn't have the time / bandwidth to answer all the questions. 

What if there was literally **ONE HOUR** a week where Justin answered questions to the contributing community and then he can be left to solve problems, tinker and innovate during the rest of the time???

Sunerok you're like the mythical Jesus figure of this whole thing whether you like it or not. Jesus built a religion by empowering his capos to spread the word and build larger followings beneath them. Obvi it went a little south with the whole Pontius Pilate situation but we all know how Christianity thrived in the long run despite it's horrible flaws and dysfunctionality. 

If this is something you want to pursue, I want to help. I'm sure @brianerdelyi and others will too. We just need you to say "do it" cause you're the fckn Steve Jarbs of this operation, man. It's open source but you are very clearly the tip of the pyramid.

OK that's it. I said my piece. Here's a [tasty song reward if you read all that](https://www.youtube.com/watch?v=CrmraIwmWu8)

TLDR: I agree we should start a foundation / more transparent governance body for VERGE, and ASAP. Sunerok just give a green light.

**Comment by brianerdelyi** [comment]
Very passionate post, thanks.  We'll have to wait for @justinvforvendetta to provide feedback and support before we can proceed.

**Comment by brianerdelyi** [comment]
@justinvforvendetta is there any leadership @vergecurrency?  Is there anyone else involved?

**Comment by Technophant** [comment]
"Everyone seems paralyzed to move without Justin's permission, and quite often Justin just doesn't have the time / bandwidth to answer all the questions."  This is the way it's been, but things are changing. Rick Stoner, a long time supporter/miner of Verge has stepped up and started managing the growing number of telegram channels and working behind the scenes to organize the large number of people working on this.

**Comment by brianerdelyi** [comment]
I have you beat by a year :). I have various business experience, have built and managed global security teams from the ground up for many large financial companies.  I’m currently consulting for various clients (financial services, retail, technology, manufacturing).

Whatever we choose to call it, an organizational structure is important to hilight who is doing what.  There are somethings that can only be done with @justinvforvendetta support and action until he is willing or able to delegate to others.

**Comment by gfranko** [comment]
This should probably not be a site issue and instead be delegated to a different forum. Closing for now.
